### ISSUE TITLE
Question: how to connect to readsb-protobuf?

### ISSUE THREAD

**Issue by klara31** [mikenye/docker-graphs1090#19]
The installation instructions are written for readsb, not for readsb-protobuf and contain some optimizations using JSON files. 

What is the best way to connect graphs1090 to readsb-protobuf?

**Comment by mikenye** [comment]
Hi @klara31,

readsb-protobuf contains its own graphs. 

In the web interface is a link for "Performance Graphs". This is basically graphs1090 modified to work with readsb-protobuf. No need to run a separate container anymore.

![image](https://user-images.githubusercontent.com/6915079/102827115-f24f7a00-441c-11eb-820f-2d166b9ef4b6.jpeg)

![image](https://user-images.githubusercontent.com/6915079/102827119-f67b9780-441c-11eb-9281-06a62ac4282b.jpeg)
